// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD13MaIoTbreNkouVCB7QBlGlbD4jU_6B0',
    appId: '1:1077236987832:android:449cb43f998c73b637814d',
    messagingSenderId: '1077236987832',
    projectId: 'kequel-app',
    storageBucket: 'kequel-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3pKE9Qg8feT0Dr3XIUPHA6yvxsYHyfUo',
    appId: '1:1077236987832:ios:abca93dfe6f6e0b237814d',
    messagingSenderId: '1077236987832',
    projectId: 'kequel-app',
    storageBucket: 'kequel-app.firebasestorage.app',
    androidClientId: '1077236987832-952tcsd7lqkq49vnj4j2kdto7642dd59.apps.googleusercontent.com',
    iosClientId: '1077236987832-lqqc6n0uj5av9kc631gp97h97qonhad5.apps.googleusercontent.com',
    iosBundleId: 'com.quoppo.kequele',
  );
}
